package com.AudioTracking.Platform.dto.analytics;

// Workspace-level snapshot: current library size (live counts on the owned tables) plus
// lifetime engagement generated by the caller (from the analytics_event log). See
// docs/analytics.md for why "totalPlays"/"totalDownloads" here mean "actions I performed",
// not "how popular my uploads are" -- that's AssetAnalyticsResponse's job.
public record AnalyticsOverviewResponse(
        long totalAssets,
        long totalProjects,
        long totalCollections,
        long totalClients,
        long totalTags,
        long totalStorageBytes,
        long totalPlays,
        long totalDownloads,
        long totalActiveCollaborators
) {
}
